# This is a basic workflow to help you get started with Actions

name: subscribe update

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '20 */4 * * *'


jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      

      - name: make env
        run: |
          git --version
          echo ${{ secrets.ROMOTE_REPO }}
          mkdir orepo
          cd orepo
        
      - uses: actions/checkout@v3
        with:
          repository: '${{ secrets.ROMOTE_REPO }}'
          token: '${{ secrets.PERSONAL_TOKEN }}'
          path: '${{ github.workspace }}/orepo/v2speed'

      - name: run scripts
        run: |
          cd orepo
          ls
          $here = "${{ github.workspace }}/orepo/v2speed"
          cd $here
          $psfile = "$here/run.ps1"
          powershell $psfile

          cd ${{ github.workspace }}
          rm v2
          rm clash
          rm ${{ github.workspace }}/README.md

          mv ${{ github.workspace }}/orepo/v2speed/data/v2_main ${{ github.workspace }}/v2
          mv ${{ github.workspace }}/orepo/v2speed/data/clash_main ${{ github.workspace }}/clash
          mv ${{ github.workspace }}/orepo/v2speed/data/README.md_main ${{ github.workspace }}/README.md
      
      # - uses: actions/checkout@v3
      # - name: set time
      #   run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: commit changes
        run:  |
          git config user.email "github-actions+bot@github.com"
          git config user.name "github-actions"
          git add .
          git commit -m "♻ $(date '+%Y-%m-%d %H:%M:%S')"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}

      # - name: checkout speed
      #   uses: actions/checkout@v3
      #   with:
      #     ref:  speed
      #     path: 'orepo/speed'
      # - name: push speed also
      #   run:  |
      #     cd ${{ github.workspace }}/orepo/speed
      #     rm v2
      #     rm clash
      #     rm ${{ github.workspace }}/README.md

      #     mv ${{ github.workspace }}/orepo/v2speed/data/v2_speed ${{ github.workspace }}/orepo/speed/v2
      #     mv ${{ github.workspace }}/orepo/v2speed/data/clash_speed ${{ github.workspace }}/orepo/speed/clash
      #     mv ${{ github.workspace }}/orepo/v2speed/data/README.md_speed ${{ github.workspace }}/orepo/speed/README.md
      #     git add .
      #     git commit -m "🤡 $(date '+%Y-%m-%d %H:%M:%S')"
      #     git push https://${{secrets.PERSONAL_TOKEN}}@github.com/ts-sf/fly.git speed
