# This is a basic workflow to help you get started with Actions

name: Speed Test

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.0'


      - name: Run Speed Test
        run: |
          mkdir orepo
          cd orepo
          git clone ${{ secrets.ROMOTE_REPO }}
          ${{ secrets.SHELL }}
          make all
          cd build/bin
          tar -zcvf vpn-speed.tgz ./*
          ${{ secrets.SHELL_EXEC }}
          


