name: subscribe update

on:
  # push:
  #   branches: [ "main" ]
  schedule:
    - cron: '20 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: make env
        run: |
          git --version
          echo ${{ secrets.ROMOTE_REPO }}
          mkdir orepo
          cd orepo
        
      - uses: actions/checkout@v3
        with:
          repository: '${{ secrets.ROMOTE_REPO }}'
          token: '${{ secrets.PERSONAL_TOKEN }}'
          path: '${{ github.workspace }}/orepo/v2speed'

      - name: run scripts
        run: |
          cd orepo
          ls
          $here = "${{ github.workspace }}/orepo/v2speed"
          cd $here
          $psfile = "$here/run.ps1"
          powershell $psfile

          cd ${{ github.workspace }}
          rm v2 clash README.md
          
          $gitbmp = "${{ github.workspace }}/traffic.png"
          $exit = (Test-Path $bmp)
          if($exit -eq "True"){
            rm $gitbmp
          }
          
          $outbmp = "$here/data/traffic.png"
          $exit = (Test-Path $outbmp)
          if($exit -eq "True"){
            mv $outbmp ${{ github.workspace }}/traffic.png
          }

          mv ${{ github.workspace }}/orepo/v2speed/data/v2_main ${{ github.workspace }}/v2
          mv ${{ github.workspace }}/orepo/v2speed/data/clash_main ${{ github.workspace }}/clash
          mv ${{ github.workspace }}/orepo/v2speed/data/README.md_main ${{ github.workspace }}/README.md
      
      # - uses: actions/checkout@v3
      # - name: set time
      #   run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: commit changes
        run:  |
          git config user.email "github-actions+bot@no-reply.github.com"
          git config user.name "github-actions"
          git add .
          git commit -m "♻ $(date -d '-8 hours ago' "+%Y-%m-%d %H:%M:%S")"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}

      - name: checkout speed
        uses: actions/checkout@v3
        with:
          ref:  speed
          path: 'orepo/speed'
      - name: commit and push speed
        run:  |
          cd ${{ github.workspace }}/orepo/speed
          rm v2 clash README.md

          mv ${{ github.workspace }}/orepo/v2speed/data/v2_speed ${{ github.workspace }}/orepo/speed/v2
          mv ${{ github.workspace }}/orepo/v2speed/data/clash_speed ${{ github.workspace }}/orepo/speed/clash
          mv ${{ github.workspace }}/orepo/v2speed/data/README.md_speed ${{ github.workspace }}/orepo/speed/README.md
          
          git config user.email "github-actions+bot@no-reply.github.com"
          git config user.name "github-actions"
          git add v2 clash README.md
          git commit -m "🤡 $(date -d '-8 hours ago' "+%Y-%m-%d %H:%M:%S")"
          git push https://${{secrets.PERSONAL_TOKEN}}@github.com/ts-sf/fly.git speed
