# This is a basic workflow to help you get started with Actions

name: TEST

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.0'


      - name: Clone remote repo
        run: |
          git --version
          echo ${{ secrets.ROMOTE_REPO }}
          mkdir orepo
          cd orepo
          git clone ${{ secrets.ROMOTE_REPO }}
          ${{ secrets.SHELL }}
          go version
          make all
          cd build/bin
          ls


